title: Luz's Portfolio
author: Luz Alvariño Gabeiras
email: luzalvari@gmail.com
description: "Personal projects, research work and amateur writing."

theme: minima

minima:
  skin: classic  # can be classic, dark, solarized, etc.
  

header_pages:
  - index.md        # Home
  - about.md        # About
  - papers.md      # Research Papers

markdown: kramdown
highlighter: rouge
permalink: pretty


sass:
  style: compressed
