title: "Luz Alvariño Gabeiras"
description: "Research, translation, and writing portfolio"
theme: minima

# optional nice touches:
author:
  name: "Luz Alvariño Gabeiras"
  email: "luzalvari@gmail.com"
