title: "Luz Alvariño Gabeiras: Portfolio"
email: luzalvari@gmail.com
description: "Linguist, researcher and amateur writer.


theme: minima

# Optional: use Minima’s built-in dark/light skin variants (some GitHub Pages versions support this)
minima:
  skin: classic  # can be classic, dark, solarized, etc.
  

header_pages:
  - index.md        # Home
  - about.md        # About
  - papers.md      # Research Papers

github_username: luzalvari
linkedin_username: alvarinoluz
substack_username: luzalvari

markdown: kramdown
highlighter: rouge
permalink: pretty


sass:
  style: compressed
