title: "Luz's Portfolio
author: Luz Alvariño Gabeiras
description: "Research, translation, and writing"
theme: minima
minima:
  skin: classic
sass:
  style: compressed
github_username: luzalvari
linkedin_username: alvarinoluz
substack_username: luzalvari
